### ISSUE TITLE
Image Resizer Permissions

### ISSUE THREAD

**Issue by seanthepottingshed** [thepottingshed/octobercms-default-theme#10]
@joshgosselin @juliangums @davethepottingshed 

@joshgosselin 

I've created release site:

* https://tps-base-theme.tps.digital

However it currently explodes whenever `resize` method is called script explodes as it can't write to destination, I've copied `ThePottingShed.ExtraFormWidgets` plugin folder from `gta.tps.digital` into `tps-base-theme.tps.digital` to ensure that it's the same versions of Intervention Image class and it's still foobarred.

I've created all the files and folders in `storage` that are present in `gta.tps.digital`

**Comment by seanthepottingshed** [comment]
@juliangums 

I'm at a total loss, for the life of me no matter where I debug the path is always just the filename - I can't actually determine which folder it's trying to write to locally.

**Comment by seanthepottingshed** [comment]
@juliangums 

Ha ha ha, it's not `storage` as would be expected, but `public`

**Comment by juliangums** [comment]
@seanthepottingshed maybe something to add to the readme of the appropriate repo

**Comment by seanthepottingshed** [comment]
@juliangums 

Yep, good idea.

**Comment by juliangums** [comment]
@seanthepottingshed i leave it to you
