### ISSUE TITLE
LESS Variable Names

### ISSUE THREAD

**Issue by seanthepottingshed** [thepottingshed/octobercms-default-theme#11]
@davethepottingshed @joshgosselin @juliangums 

I propose that we rename the following variables:

* `@primaryFont` -> `@titleFont`
* `@secondaryFont` -> `@bodyCopyFont`
* `@primaryFontColour` -> `@bodyCopyColour`
* `@secondaryFontColour` -> `@titleColour`
* `@primaryLinkColour` -> `@linkColour`
* `@secondaryLinkColour` -> `@hoverColour`

I find myself getting massively confused between them - but hey I am getting on a bit.

**Comment by juliangums** [comment]
@seanthepottingshed maybe `paragraph` instead of `bodyCopy`?

**Comment by seanthepottingshed** [comment]
@juliangums 

Could do, although this would be used for lists so it's no strictly paragraphs.

**Comment by juliangums** [comment]
@seanthepottingshed I know but `titleFont` could be used for elements other than <h1-6> titles. Sure, lists aren't paragraphs but it seems obvious they would have the same font. It is still a fairly generic naming but everyone gets it immediately.

**Comment by seanthepottingshed** [comment]
@juliangums 

`paragraphFont` doesn't apply here as it actually cascades to other elements such as `<ul>` etc...

**Comment by juliangums** [comment]
@seanthepottingshed yeah no problem. to me they all make sense. just use the one you like
