### ISSUE TITLE
About Page Content

### ISSUE THREAD

**Issue by seanthepottingshed** [thepottingshed/octobercms-default-theme#15]
@joshgosselin 

I know I've asked this before, but what is the actual content for the about page:

* https://tps-base-theme.tps.digital

**Comment by joshgosselin** [comment]
Just gonna be a couple of content blocks.. Similar to GTA I think.. 
Intro - text block
Our Vision & Values - text block
Our History Timeline
Key Contacts

**Comment by seanthepottingshed** [comment]
@joshgosselin 

Forgot all about Timeline!

**Comment by joshgosselin** [comment]
You shouldn’t its well sexy
