### ISSUE TITLE
Adding basic folder structure, header and footer partial in default theme

### ISSUE THREAD

**Issue by seanthepottingshed** [thepottingshed/octobercms-default-theme#5]
@juliangums commented on [Thu Jan 12 2017](https://github.com/thepottingshed/general/issues/22)

**Comment by juliangums** [comment]
this will help a lot. can you add this?

**Comment by seanthepottingshed** [comment]
@juliangums

Once I've finished Privacy Policy plugin and caught up with JEMEC will have a crack at this.

**Comment by juliangums** [comment]
@seanthepottingshed thanks
