### ISSUE TITLE
gulpfile.js

### ISSUE THREAD

**Issue by seanthepottingshed** [thepottingshed/octobercms-default-theme#6]
@seanthepottingshed commented on [Tue May 30 2017](https://github.com/thepottingshed/octobercms-set-up-script/issues/14)

Use JSHint as part of the build process?

https://github.com/done/laravel-elixir-jshint

**Comment by seanthepottingshed** [comment]
@juliangums 

Can close this now, as using `theme.yaml` method using OctoberCMS LESS compiler. eg:

* https://github.com/thepottingshed/jemec/blob/develop/themes/jemec/theme.yaml

**Comment by juliangums** [comment]
ah ok, so is the pjax plugin pulling it from there?

**Comment by seanthepottingshed** [comment]
@juliangums 

Yes, basically the pJax plugin compiles the less files references from theme.less refer to here:

* https://github.com/thepottingshed/octobercms-pjax-framework-plugin
