### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by juliangums** [thepottingshed/octobercms-default-theme#8]
can the assets be reviewed especially the images

**Comment by juliangums** [comment]
@seanthepottingshed I'm not doing this in the setup script
```
assets/images/backend-ui/loader-transparent.svg -> {{ BrandPrimaryColor }} would need to be replaced with a color hex value
```

isn't this being handled somwhere else? do we need the backend-ui folder in her at all?

**Comment by seanthepottingshed** [comment]
@juliangums 

This is invalid, I've since created a backend route which serves a branded loader SVG.

**Comment by juliangums** [comment]
yeah just realised after i deleted the backend-ui folder. we would just need some default partials then right? maybe even a default static page for `/` and error pages? https://github.com/thepottingshed/octobercms-default-theme/issues/5
